name=jesl
version=0.1.0
author=James Aguilar <aguilar.james@gmail.com>
maintainer=James Aguilar <aguilar.james@gmail.com>
sentence=James' Embedded Support Library
paragraph=A library for embedded systems support.
category=Utility
url=https://github.com/jaguilar/jesl
architectures=*
